### ISSUE TITLE
Help adding entries to the database

### ISSUE THREAD

**Issue by MincePie** [unixisking/boilerplate-task#3]
Hi @unixisking , 

Would you be willing to give me another consulting session to help me figure out the steps to post to the psql database. I'm getting stuck implementing what you gave  me via upwork. 

i'd like to share my screen with you and for you to show me how to complete the next steps. I'd be happy to pay you $200 via paypal for the help, if that's okay with you?

Thanks
Mel

**Comment by unixisking** [comment]
> Hi @unixisking , 
> 
> Would you be willing to give me another consulting session to help me figure out the steps to post to the psql database. I'm getting stuck implementing what you gave  me via upwork. 
> 
> i'd like to share my screen with you and for you to show me how to complete the next steps. I'd be happy to pay you $200 via paypal for the help, if that's okay with you?
> 
> Thanks
> Mel

Hello @MincePie

I hope you're doing well!

Yes, we can schedule a session this week, please share with me your address that way we can agree on the date there.

Looking forward to it!
Sid Ahmed
